### ISSUE TITLE
Should this work on Windows?

### ISSUE THREAD

**Issue by maelle** [lorenzwalthert/gitsum#33]
A very short question, the package doesn't work on Windows yet, does it? (judging from my own laptop + the Appveyor build)

**Comment by lorenzwalthert** [comment]
It worked at some stage on @jonmcalder 's windows machine 😊. Now the appveyor build of master is passing again but I needed to skip some steps because I could not get them going and I could not find out why. It's kind of hard to test these things because for a full test, you need to create git repositories in the `test` directory and make sure you don't mess with paths. On travis, it seems to work but not on windows. Also, as it says in the README, the project is experimental still. Once I have a Windows machine available, I will try to make it work there too. 
Where does it fail on your machine?

**Comment by lorenzwalthert** [comment]
PRs are welcome if you figure out how to fix the problems.

**Comment by maelle** [comment]
Will report better tomortow but basically with `parse_log_detailed` it says sthg like "this is not a gitsum repo".

Due to other commit(ment)s😉 I can only test and report, not contribute, sorry. Happy to wait a while, I understand it's a work in progress! 😀

**Comment by lorenzwalthert** [comment]
Did you `gitsum::init_gitsum()`?

**Comment by lorenzwalthert** [comment]
I think as of now, you need to initiate a gitsum repository with the above mentioned command in the directory (which means adding a `.gitsum` folder, parsing the log and caching it) before you can manually parse a log with `gitsum::parse_log_detailed()` (which essentially retrieves the cached log and parses new commits that are not yet cached). Probably need to change that so you can also parse a log without caching it.

**Comment by maelle** [comment]
Oh yes sorry I had and the error was something related to the export command via system (am AFK, could look again tomorrow) which does look OS specific. Sorry not to be more precise right now!

**Comment by lorenzwalthert** [comment]
Never mind, we are not in a hurry. Let's figure it out when you have time.

**Comment by lorenzwalthert** [comment]
We still need to think of ways to test this (#23).

**Comment by lorenzwalthert** [comment]
@maelle let me know whether or not it works for you.

**Comment by maelle** [comment]
It works 😍 ! This makes me very happy, thanks a ton! 

Should I close the issue?

**Comment by maelle** [comment]
Oh I can't close it anyway. :joy:

**Comment by lorenzwalthert** [comment]
Glad to hear that.
