### ISSUE TITLE
Compare commit author names with DESCRIPTION's `Authors@R: person(…)`

### ISSUE THREAD

**Issue by katrinleinweber** [lorenzwalthert/gitsum#38]
Over time, a package's metadata in the `DESCRIPTION` may diverge from the actual content of the repo. For example, contributors might substantially add to the package, which at least in the academic world would at some point raise the question of co-author-/-maintainer-ship.

How do you feel about adding a helper-function, which compares the parsed author names with `Authors@R: person(…)` and shows a warning in case some (yet to be defined) mismatch is found? The mismatch could be: top Nth contributor is not in `DESCRIPTION`, but top (N-1)th is.

**Comment by lorenzwalthert** [comment]
Hi @katrinleinweber, thanks for the suggestion. However, I am not sure if gitsum is the right place for that. Would it just be a standalone function? It is a very specific functionality, and I wonder if it's not better to create that on the fly. gitsum is also not restricted to analyse R package repos. It can parse any git repository. There is an ropenscience package that does some checks for packages that `devtools::release()`does not because they are best practices but not strictly required. Maybe it could fit there? Unfortunately, I can't find the package anymore. As far as parsing the DESCRIPTION goes, one can use the `desc` package.

**Comment by katrinleinweber** [comment]
I was thinking of a warning within a related function, not a stand-alone one. Yeah, `desc` or `devtools` might be better suited. Thanks for the hint :-)

**Comment by lorenzwalthert** [comment]
Ah this is the one I meant I think: https://github.com/MangoTheCat/goodpractice

**Comment by lorenzwalthert** [comment]
I just don't know when I will submit `gitsum` to CRAN.
